'use strict';

/**
 * Attributes, generated by random.
 * Must be removed from the generated static html-page for correct testing of distributives in platform tests.
 * https://online.sbis.ru/opendoc.html?guid=2b25dbee-be00-4c07-b101-db3af72c80b0
 */
const TEST_ATTRS = ['config'];

const Application = require('../wasaby/application');

/**
 * Class with main functions and parameters for platform templates
 * constructor that's generating .html.tmpl/.wml/.tmpl files.
 * @author Kolbeshin F.A.
 */
class TemplatesBuilder {
   constructor() {
      this.app = new Application();

      // common template's constructor functions. Null by default
      this.CompilerLib = null;
      this.ViewBuilderTmpl = null;
      this.ViewConfig = null;
      this.Compiler = null;
   }

   // requires basic platform needed by .wml/.tmpl/.html.tmpl compiler.
   requireView() {
      this.app.init();

      if (!this.CompilerLib) {
         this.CompilerLib = global.requirejs('Compiler/Compiler');

         this.ViewBuilderTmpl = this.CompilerLib.Tmpl;
         this.ViewConfig = this.CompilerLib.Config;
         this.Compiler = this.CompilerLib.Compiler;
      }
   }

   async render(options) {
      const config = {
         ...this.app.requestConfig,
         ...options
      };

      const html = await this.app.startRequest(
         'Router/Builder',
         ({ renderStatic }) => renderStatic(config)
      );

      return removeHtmlAttrs(html, TEST_ATTRS);
   }

   setCommonRootInfo(serviceConfig) {
      this.app.setRequestConfig(serviceConfig);
   }
}

module.exports = TemplatesBuilder;

/**
 * Removes transmitted attributes from html-pages
 * @param {string} html
 * @param {string[]} attrs
 */
function removeHtmlAttrs(html, attrs) {
   return attrs.reduce((prev, attr) => prev.replace(new RegExp(` ${attr}=["|'][^\\s+]+(\\s+[^\\s+])*["|']`, 'gi'), ''), html);
}
